[package]
name = "lesson_2"
version = "0.32.0"
authors = ["taidaesal"]
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive", "extern_crate_std", "min_const_generics"] }
vulkano = "0.32.0"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
winit = "0.27.3"
