[package]
name = "lesson_13"
version = "0.26.0"
authors = ["taidaesal"]
edition = "2021"

[dependencies]
png = "0.17.2"
vulkano = "0.26.0"
winit = "0.25.0"
vulkano-win = "0.26.0"
vulkano-shaders = "0.26.0"
nalgebra-glm = "0.15.0"
